services:
  proxy_lb:
    container_name: proxy_lb
    image: nginx:latest
    ports:
      - '${PROXY_PORT:-80}:80'
      - '${PROXY_PORT_SSL:-443}:443'
    volumes:
      - './config/nginx/proxy_lb.conf:/etc/nginx/conf.d/default.conf'
    networks:
      - c3d_net
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 2
    expose:
      - '${FORWARD_APP_PORT:-3000}'
    networks:
      - c3d_net

volumes:
  c3d_vol:
    driver: local

networks:
  c3d_net:
    driver: bridge
